---
title: "Stroop Task Summary"
author: "Janey Matejka, Rebecca Lee, Kayleah Tsai"
date: "2022-10-06"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
rm(list = ls(all.names = TRUE))      # remove objects in R
# set the paths for project, script, and data dirs
this_rmd_path <- rstudioapi::getActiveDocumentContext()$path
proj_dir <- gsub("GCDS.*.Rmd", "GCDS", this_rmd_path)
proj_name = ""
library(magrittr)
library(dplyr)
r_dir    <- paste(proj_dir, "r", sep = "/")          # r subdir
data_dir <- paste(proj_dir, "data", sep = "/")       # data subdir
#source("https://pastebin.com/raw/b63hB7Hj")         # get all externals
#source("https://pastebin.com/raw/8mXH02yg")   # run and comment out after knitting
source("https://pastebin.com/raw/97NNTTzu")   # run to include in function definitions 
```

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r}
stroopdat <- read_csv("gcds_stroop_project_data.csv")
stroopdat <- select(stroopdat, -valence)
stroopdat <- select(stroopdat, -(wf_kf:domin_sd))
stroopdat <- filter(stroopdat, id != 0)
cleanStroopDat <- stroopdat

view(stroopdat)
```

```{r}
stroopdat <- stroopdat %>%
  mutate(., key_color =
           case_when(
             resp == 'd' ~ 'blue',
             resp == 'f' ~ 'green', 
             resp == 'j' ~ 'orange',
             resp == 'k' ~ 'yellow'
           )) %>%
   mutate(., congruency = 
           case_when(
           font == word ~ 'CONGRUENT', 
           font != word ~ 'INCONGRUENT'))%>%
  
  mutate(., accurate =
           case_when(
             font == key_color ~ 'ACCURATE', 
             font != key_color ~ 'INACCURATE'
           ))
 

view(stroopdat)
```

```{r}
write_csv(stroopdat, 'gcds_stroop_10_06_accuracy.csv')
```

```{r}
stroopdat <- stroopdat %>%
  filter(., block == 'stroop')
```

```{r}
view(stroopdatWAccRate <- stroopdat %>%
       group_by (id, congruency, accurate) %>%
       summarise(n = n()) %>%
       mutate(AccRate = n/sum(n))%>%
       filter(., accurate == 'ACCURATE')
     )
```

```{r}
view(stroopdatWAccRate <- stroopdatWAccRate %>% 
       group_by(id) %>%
       mutate(., stroopAcc = AccRate - lag(AccRate)))
```




```{r}
view(stroopdatWRespLat <- stroopdat %>%
  group_by(id, congruency) %>%
  mutate(., rtMean = mean(rt), rtLatency = rt - rtMean)%>% 
  filter(., accurate == "ACCURATE")) 
```

```{r}
view(stroopdatWRespLat <- stroopdatWRespLat %>%
       group_by(id) %>%
       mutate(., SIErtLatency = rtMean - lag(rtMean)))
```


```{r}
view(stroopSummAccRate <-
       stroopdatWAccRate %>%
       group_by(congruency) %>%
       summarise(meanAccRate = mean(AccRate)))
```

```{r}
view(stroopSummRTLatency <- stroopdatWRespLat %>%
       group_by(congruency) %>%
       summarise(meanRT = mean(rtMean)))
```

```{r}
view(giantstroop <- left_join(stroopdatWAccRate, stroopdatWRespLat))
```

```{r}
view(stroopSumSIE <- giantstroop %>%
       group_by(congruency)%>%
       summarise( meanSIEacc = mean(stroopAcc, na.rm = TRUE), meanSIElat = mean(SIErtLatency, na.rm = TRUE) ))

```

```{r}

```



